#!/bin/bash

echo "Beginning storage check"

echo "Date$(date)"

echo "-----------------"

echo "Enter disk name in sd format (eg sda1, sda2, sda3):"

read varname 

part=/dev/$varname

checkper=$(df -h | grep $part | awk '{print $5} | cut '%' -f1)

echo "$part is $checkper% full"

echo "storage check complete"
